name: Deploy to GitHub Pages

on:
  push:
    branches: "main" # 监听 main 分支的推送

# 设置 GitHub Actions 的权限
permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  build_site:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20 # 使用稳定的 Node 版本
          cache: 'npm'

      - name: Install dependencies
        run: npm install

      - name: Build
        run: npm run build # 这里的命令对应 package.json 里的构建脚本

      - name: Upload Artifacts
        uses: actions/upload-pages-artifact@v3
        with:
          path: dist # Vite 默认编译输出的文件夹是 dist

  deploy:
    needs: build_site
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - name: Deploy
        id: deployment
        uses: actions/deploy-pages@v4